# Generated by Django 5.1.7 on 2025-03-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_time',
        ),
        migrations.AddField(
            model_name='shift',
            name='day',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='volunteer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
