# Generated by Django 5.1.7 on 2025-04-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_shift_volunteer_workerassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_index',
            field=models.CharField(max_length=20),
        ),
    ]
