# Generated by Django 5.1.7 on 2025-04-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_remove_workerassignment_name_shiftassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('limit', models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
