# Generated by Django 5.1.7 on 2025-04-25 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_timeslot_alter_shiftassignment_time_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'verbose_name': 'Vakt', 'verbose_name_plural': 'Vakter'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['order'], 'verbose_name': 'Tidsluke', 'verbose_name_plural': 'Tidsluker'},
        ),
        migrations.AlterModelOptions(
            name='volunteerlimit',
            options={'verbose_name': 'Frivilliggrense', 'verbose_name_plural': 'Frivilliggrenser'},
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='date',
            field=models.DateField(verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='role',
            field=models.CharField(choices=[('worker', 'Ansatt'), ('volunteer', 'Frivillig')], max_length=10, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.timeslot', verbose_name='Tidsluke'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bruker'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_weekend',
            field=models.BooleanField(default=False, verbose_name='Helg?'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tidspunkt'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Rekkefølge'),
        ),
        migrations.AlterField(
            model_name='volunteerlimit',
            name='date',
            field=models.DateField(unique=True, verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='volunteerlimit',
            name='limit',
            field=models.PositiveIntegerField(default=2, verbose_name='Grense for frivillige'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=100)),
                ('workers', models.ManyToManyField(blank=True, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
