# Generated by Django 5.1.7 on 2025-04-28 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_alter_shiftassignment_options_alter_timeslot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
