# Generated by Django 5.1.7 on 2025-04-28 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_shiftassignment_workers_delete_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftassignment',
            name='workers',
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=100)),
                ('workers', models.ManyToManyField(related_name='assigned_shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
