# Generated by Django 5.1.7 on 2025-05-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('volunteer', 'Volunteer')], max_length=10),
        ),
    ]
