# Generated by Django 5.1.7 on 2025-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0012_userprofile_bio_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Tidspunkt'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('label', 'is_weekend')},
        ),
    ]
