# Generated by Django 5.1.7 on 2025-10-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0013_alter_timeslot_label_alter_timeslot_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Vakt', 'verbose_name_plural': 'Vakter'},
        ),
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'verbose_name': 'Vaktoppgave', 'verbose_name_plural': 'Vaktoppgaver'},
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
