# Generated by Django 5.1.7 on 2025-10-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0014_alter_shift_options_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='comment',
        ),
    ]
